services:
  php-form:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./src/users.json:/var/www/html/users.json
    restart: unless-stopped
